# Generated by Django 6.0 on 2025-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_birth_cert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth_cert',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='birth_cert',
            name='home_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='birth_cert',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='birth_cert',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='birth_cert',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='birth_cert',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='birth_cert',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
