# Generated by Django 6.0 on 2025-12-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_birth_cert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth_cert',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
