# Generated by Django 6.0 on 2025-12-09 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_birth_cert_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birth_cert',
            new_name='Birth_certificate',
        ),
    ]
