# Generated by Django 5.2.8 on 2025-12-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_birth_cert_birth_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_type', models.CharField(choices=[('statutory_marriage', 'Statutory Marriage'), ('customary_marriage', 'Customary Marriage'), ('renewal_of_vows', 'Renewal Of Vows')], max_length=30)),
                ('groom_full_name', models.CharField(max_length=40)),
                ('groom_dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=15)),
                ('groom_occupation', models.CharField(max_length=50)),
                ('groom_residence', models.CharField(max_length=100)),
                ('bride_full_name', models.CharField(max_length=40)),
                ('bride_deb', models.DateField()),
                ('bride_marital_status', models.CharField(choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=15)),
                ('bride_occupation', models.CharField(max_length=50)),
                ('bride_residence', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='birth_certificate',
            options={'verbose_name': 'Birth Certificate', 'verbose_name_plural': 'Birth Certificates'},
        ),
    ]
